version: '3'
services:
  bitcoind-regtest:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin-regtest
    ports:
      - "18443:18443"
      - "18444:18444" 
    command: ["bitcoind","-regtest=1", "-printtoconsole","-rpcuser=username","-rpcpassword=password"]
